<a href="https://colab.research.google.com/github/abdelilah-bouslama/Data-Science/blob/master/numpy/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **Example 1**

In [0]:
import numpy as np
Array = np.array([1,2,3])
print(type(Array),Array, Array.ndim, Array.size, Array.shape)

<class 'numpy.ndarray'> [1 2 3] 1 3 (3,)


In [0]:
dims = np.array([[1,2,3],[4,5,6]])
print(type(dims),dims, dims.ndim, dims.size, dims.shape, dims.itemsize)
dims[:,1] = 10
dims[1,:] = 25
print(dims)

In [0]:
print(np.sort(dims))

## **Example 2**

In [0]:
ar = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(type(ar), ar)
print("dimension is %d "%ar.ndim)
print("size is %d "%ar.size)
print("shape is ",ar.shape)
print("type is ", ar.dtype)

In [0]:
print(ar[1:],ar[1,:], ar[1,2])

In [0]:
print(ar[1:3])
print(ar[1,2])
#print(ar[1,::2])
#print(ar[::-1])
#print(ar[:,::-1])

In [0]:
import numpy as np
ar = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(ar.shape)
print(ar[1,1])
print(ar[2,:])
print(ar[::-1])
print(ar[1,::2])
print("dimension is %d "%ar.ndim)

In [0]:
print(ar[1,::-1])

[6 5 4]


In [0]:
a=np.arange(6).reshape(3,2)
b=np.arange(6,12).reshape(3,2)
c= a*b
print(type(c), c.ndim, c.dtype, a.size)
print(np.vstack((a,b)))
print(np.hstack((a,b,c)))
print(np.zeros((4,3),dtype=int))
print(c > 12, c[(a*b) > 12])

In [0]:
tab1 = np.array([[1,2,3],[4,5,6]])
tab2 = np.array([[7,8,9]])
print(tab1.shape)
zeros = np.zeros((tab1.shape), dtype=int) 
tab2 = zeros + tab2
print(tab2)
print(tab1+tab2)
print(tab1[1,::-1])

**EXERCICES**

In [0]:
a=np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [0]:
b=np.ones(10)
b

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [0]:
c= np.ones(10)*5
c

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [0]:
d=np.arange(10,51,dtype=int)
d

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [0]:
e=np.arange(10,51,2, dtype=int)
e

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [0]:
f=np.arange(9).reshape(3,3)
f

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [0]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [0]:
np.random.randn(1,25)

array([[-0.5310795 , -0.48281902,  1.00613449,  1.53622431, -1.39332896,
        -1.4126402 ,  0.61892985,  0.31230619, -0.26282784,  0.73699419,
        -0.97507841, -1.37150826,  0.43886389, -0.06500246, -0.28561892,
         0.42963301, -0.19493607,  0.2739154 ,  1.50274692,  0.3274144 ,
        -0.46126391, -0.82091212, -1.14279058, -2.29063871,  0.34853499]])

In [0]:
np.arange(100).reshape(10,10)/100
np.linspace(0.1,1,100).reshape(10,10)

array([[0.1       , 0.10909091, 0.11818182, 0.12727273, 0.13636364,
        0.14545455, 0.15454545, 0.16363636, 0.17272727, 0.18181818],
       [0.19090909, 0.2       , 0.20909091, 0.21818182, 0.22727273,
        0.23636364, 0.24545455, 0.25454545, 0.26363636, 0.27272727],
       [0.28181818, 0.29090909, 0.3       , 0.30909091, 0.31818182,
        0.32727273, 0.33636364, 0.34545455, 0.35454545, 0.36363636],
       [0.37272727, 0.38181818, 0.39090909, 0.4       , 0.40909091,
        0.41818182, 0.42727273, 0.43636364, 0.44545455, 0.45454545],
       [0.46363636, 0.47272727, 0.48181818, 0.49090909, 0.5       ,
        0.50909091, 0.51818182, 0.52727273, 0.53636364, 0.54545455],
       [0.55454545, 0.56363636, 0.57272727, 0.58181818, 0.59090909,
        0.6       , 0.60909091, 0.61818182, 0.62727273, 0.63636364],
       [0.64545455, 0.65454545, 0.66363636, 0.67272727, 0.68181818,
        0.69090909, 0.7       , 0.70909091, 0.71818182, 0.72727273],
       [0.73636364, 0.74545455, 0.7545454

In [0]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [0]:
mat=np.arange(1,26).reshape(5,5)
mat[2:,1:]
mat[3,4]

20

In [0]:
mat[0:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [0]:
mat[-1]

array([21, 22, 23, 24, 25])

In [0]:
mat[3:,:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [0]:
mat.sum()

325

In [0]:
mat.min()

1

In [0]:
np.full((2,4), 23)

array([[23, 23, 23, 23],
       [23, 23, 23, 23]])

In [0]:
mat = np.array([[1,2,3],[4,5,6],[7,8,9]])
np.rot90(mat)
np.rot90(mat, -1)

array([[7, 4, 1],
       [8, 5, 2],
       [9, 6, 3]])

In [0]:
np.diag(np.array([3,3,3]))

array([[3, 0, 0],
       [0, 3, 0],
       [0, 0, 3]])

In [0]:
np.diag(mat)

array([1, 5, 9])

EXERCICES II

In [0]:
#Question 1: Create a 4X2 integer array and Prints its attributes
ar = np.arange(1,9).reshape(4,2)
print(ar)
ar.ndim
ar.dtype
ar.size
ar.itemsize
np.linspace(1,8,8,dtype=int).reshape(4,2)

In [0]:
#Question 2: Create a 5X2 integer array from a range between 100 to 200 such that the difference between each element is 10
ar = np.arange(100,200,10).reshape(5,2)
ar2 = np.linspace(100,190,10,dtype=int).reshape(5,2)
print(ar)
print(ar2)

In [0]:
#Question 3: Following is the provided numPy array. return array of items in the third column from all rows
sampleArray = np.array([[11 ,22, 33], [44, 55, 66], [77, 88, 99]])
sampleArray[:,2]

array([33, 66, 99])

In [0]:
#Question 4: Following is the given numpy array return array of odd rows and even columns
sampleArray = np.array([[3 ,6, 9, 12], [15 ,18, 21, 24], 
[27 ,30, 33, 36], [39 ,42, 45, 48], [51 ,54, 57, 60]])
sampleArray[::2,1::2]

In [0]:
#Question 5: Add the following two NumPy arrays and Modify a result array by calculating the square of each element
arrayOne = np.array([[5, 6, 9], [21 ,18, 27]])
arrayTwo = np.array([[15 ,33, 24], [4 ,7, 1]])
arryResult = arrayOne + arrayTwo
print(np.square(arryResult))
arryResult*arryResult

In [0]:
#Question 6: Split the array into four equal-sized sub-arrays
#Create an 8X3 integer array from a range between 10 to 34 such 
#that the difference between each element is 1 and then Split the array into four equal-sized sub-arrays.
ar = np.arange(10,34).reshape(8,3)
re = np.split(ar,4)
re

In [0]:
#Question 7; Sort following NumPy array
#7.1- by the second row and
#7.2-by the second column
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
re = sampleArray.sort(axis=1)
sampleArray

In [0]:
#Question 8: Following is the 2-D array. Print max from axis 0 and min from axis 1
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
np.amin(sampleArray, 1)
np.amax(sampleArray, 0)
np.em

array([82, 94, 73])

In [0]:
#Question 1: Create a 4X2 integer array and Prints its attributes
#Question 2: Create a 5X2 integer array from a range between 100 to 200 such that the difference between each element is 10
#Question 3: Following is the provided numPy array. return array of items in the third column from all rows
sampleArray = np.array([[11 ,22, 33], [44, 55, 66], [77, 88, 99]])
#Question 4: Following is the given numpy array return array of odd rows and even columns
sampleArray = np.array([[3 ,6, 9, 12], [15 ,18, 21, 24], 
[27 ,30, 33, 36], [39 ,42, 45, 48], [51 ,54, 57, 60]])
#Question 5: Add the following two NumPy arrays and Modify a result array by calculating the square of each element
arrayOne = np.array([[5, 6, 9], [21 ,18, 27]])
arrayTwo = np.array([[15 ,33, 24], [4 ,7, 1]])
#Question 6: Split the array into four equal-sized sub-arrays
#Create an 8X3 integer array from a range between 10 to 34 such 
#that the difference between each element is 1 and then Split the array into four equal-sized sub-arrays.
#Question 7; Sort following NumPy array
#7.1- by the second row and
#7.2-by the second column
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
#Question 8: Following is the 2-D array. Print max from axis 0 and min from axis 1
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])

[ 3 18 33 48]
